### ISSUE TITLE
appareance rotated with dvips if document is in landscape 

### ISSUE THREAD

**Issue by u-fischer** [latex3/pdfresources#24]
~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata {uncompress}
\documentclass[landscape]{article}
\usepackage{l3pdffield-testphase}
\begin{document}
\special{papersize=\the\paperwidth,\the\paperheight}
test landscape
\ExplSyntaxOn
\pdffield_appearance:nn {pdffield/test/Yes}{Y}

\pdffield_appearance:nn {pdffield/test/Off}{W}
  
\pdffield_checkbox:n{name=test,width=5cm,height=3cm,appearance=pdffield/test}
\ExplSyntaxOff

\end{document}
~~~~

gives 

![image](https://user-images.githubusercontent.com/4047173/126535346-7474c8d9-86c8-4415-87e8-c0ec0dd4ac1e.png)

The main problem is that dvips is actually cheating when setting the paper size. The media box is portrait and it rotates it:

~~~~
<</Type/Page/MediaBox [0 0 612 792] /Rotate 270 ....
~~~~

One can avoid it 

* by using a papersize which is slightly off different to the portrait values
* by defining in config.ps a proper landscape page size
~~~~
@ letterlandscape 11in 8.5in 
@+ ! %%DocumentPaperSizes: Letterlandscape
@+ %%BeginPaperSize: Letterlandscape
@+ /setpagedevice where
@+  { pop << /PageSize [792 612] >> setpagedevice }
@+ if
@+ %%EndPaperSize
~~~~

which is then used for the mediabox.

* by some clever postscript?

Related discussion on the texlive list: https://tug.org/pipermail/tex-live/2021-July/047291.html

**Comment by agrahn** [comment]
The most robust approach is perhaps replicating all existing paper format entries in `config.ps` with swapped paper width and height values. Otherwise, `dvips` automatically inserts the DSC comment `%%Orientation: Landscape` at the top of the PS output when it finds a matching Portrait paper format entry in `config.ps`. This cannot be undone by adding clever PostScript, it seems. Eventually, the DSC comment `%%Orientation: Landscape` signals to `ps2pdf` to add `/Rotate 90` to the Page dictionary, with the implications Ulrike described.

**Comment by u-fischer** [comment]
dvips will probably change its behaviour in texlive 2022 here. So waiting for now.

**Comment by u-fischer** [comment]
looks ok in texlive 2022.
