### ISSUE TITLE
pdfproducer and pdfcreator default values written, despite intentionally having been left blank

### ISSUE THREAD

**Issue by igreil** [latex3/pdfresources#27]
I hesitate to call this one a bug, but the behavior differs from my previous setup and `hyperref` behavior:

```
% !TeX program  = lualatex

\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{pdfstandard=A-2U}

\documentclass{article}

\usepackage{fontspec}
\usepackage{hyperxmp}
\usepackage[pdfa]{hyperref}   

\hypersetup{
	pdftitle={Foobar},
	pdfproducer={}, 	% Intentionally set to empty
	pdfcreator={},		% Intentionally set to empty
}
	
\pdfvariable omitcidset=1

\begin{document}
	Lorem ipsum dolor sit amet.
\end{document}
```

Even though I have explicitly set `pdfproducer` and `pdfcreator` to empty values, the defaults of "LuaTeX-1,13,2" and "TeX" are written to the PDF meta data. This previously was only the case if these keys were omitted from hypersetup altogether.

**Comment by u-fischer** [comment]
I will add a test. But basically it isn't the right way to suppress this info with luatex. If you really want to suppress the fields use `
`\pdfvariable suppressoptionalinfo \numexpr 128 + 16 \relax`.  (Sadly the backends and engines differ a lot here, and so no common method exist).

Btw: don't use the pdfa option with the pdfmanagement (it won't harm but it does nothing). Use the pdfstandard key to set the standard. 

Also be aware that some changes are intentional. The new hyperref driver used here does change things.

**Comment by igreil** [comment]
> Btw: don't use the pdfa option with the pdfmanagement (it won't harm but it does nothing). Use the pdfstandard key to set the standard.

Thanks for spotting the stray error.
> Also be aware that some changes are intentional. The new hyperref driver used here does change things.

Fair enough. Thanks for your efforts.

**Comment by u-fischer** [comment]
This has been resolved. creator and producer are  empty.
